image: node:10-alpine # use nodejs v10 LTS
cache:
  paths:
    - node_modules/

before_script:
  - npm install hexo-cli -g
  - npm install

pages:
  script:
    - hexo generate
    - npm install
    - ./node_modules/hexo/bin/hexo clean
    - ./node_modules/hexo/bin/hexo generate
    - ./node_modules/hexo/bin/hexo deploy
  artifacts:
    paths:
      - public
  only:
    - main
